# Generated by Django 2.1 on 2018-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180921_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('RU', 'русский'), ('HI', 'история'), ('GE', 'география'), ('PH', 'физика')], default='RU', max_length=2, verbose_name='Тема'),
        ),
    ]
