# Generated by Django 2.1 on 2018-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('RU', 'русский язык'), ('HI', 'история'), ('GE', 'география'), ('PH', 'физика')], default='RU', max_length=2, verbose_name='Тема'),
        ),
    ]
