# Generated by Django 2.1 on 2018-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180921_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('RUSSIAN', 'русский язык'), ('HISTORY', 'история'), ('GEOGRAPHY', 'география'), ('PHYSICS', 'физика')], default='RUSSIAN', max_length=2, verbose_name='Тема'),
        ),
    ]
